In [13]:
import numpy as np
import pandas as pd

In [14]:
data=pd.read_csv("/home/user/Downloads/diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [15]:
x=data.iloc[:,:-1].values
print(x)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [16]:
y=data.iloc[:,-1].values
print(y)

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=2)
print(x_train)

[[3.000e+00 8.400e+01 7.200e+01 ... 3.720e+01 2.670e-01 2.800e+01]
 [0.000e+00 1.180e+02 6.400e+01 ... 0.000e+00 1.731e+00 2.100e+01]
 [1.000e+01 9.200e+01 6.200e+01 ... 2.590e+01 1.670e-01 3.100e+01]
 ...
 [4.000e+00 1.250e+02 7.000e+01 ... 2.890e+01 1.144e+00 4.500e+01]
 [3.000e+00 1.160e+02 7.400e+01 ... 2.630e+01 1.070e-01 2.400e+01]
 [4.000e+00 1.100e+02 6.600e+01 ... 3.190e+01 4.710e-01 2.900e+01]]


In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
print(x_train)

[[-2.88114829e-01 -1.22309245e+00  1.29331617e-01 ...  6.79078156e-01
  -6.27909087e-01 -4.56474754e-01]
 [-1.17053496e+00 -1.33658264e-01 -2.97731125e-01 ... -4.06810020e+00
   3.52432104e+00 -1.05392900e+00]
 [ 1.77086548e+00 -9.66754997e-01 -4.04496811e-01 ... -7.62941076e-01
  -9.11531363e-01 -2.00422933e-01]
 ...
 [ 6.02521506e-03  9.06370102e-02  2.25659317e-02 ... -3.80104112e-01
   1.85945828e+00  9.94485562e-01]
 [-2.88114829e-01 -1.97742628e-01  2.36097303e-01 ... -7.11896147e-01
  -1.08170473e+00 -7.97877181e-01]
 [ 6.02521506e-03 -3.89995720e-01 -1.90965440e-01 ...  2.73285232e-03
  -4.93196428e-02 -3.71124147e-01]]


In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [20]:
y_predict=knn.predict(x_test)


In [21]:
print(knn.predict([[5,148,72,35,94,28,0.167,25]]))

[1]


In [22]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_predict)
print(result)
result1=accuracy_score(y_test,y_predict)
print(result1)

[[134  21]
 [ 40  36]]
0.7359307359307359


In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.77      0.86      0.81       155
           1       0.63      0.47      0.54        76

    accuracy                           0.74       231
   macro avg       0.70      0.67      0.68       231
weighted avg       0.72      0.74      0.72       231

